// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPOkzLYWPe1eegoXfWu6y3qRvE4cRqvPA',
    appId: '1:301900713627:web:ebede2249ba340939bc03e',
    messagingSenderId: '301900713627',
    projectId: 'chatapplication-47e35',
    authDomain: 'chatapplication-47e35.firebaseapp.com',
    storageBucket: 'chatapplication-47e35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCAJzCL96FTkJGRQvre3zGCwLdQHafBek',
    appId: '1:301900713627:android:9a468e3e1039f75f9bc03e',
    messagingSenderId: '301900713627',
    projectId: 'chatapplication-47e35',
    storageBucket: 'chatapplication-47e35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSqDB2rD0hgD-tPf10MzrGALNVBL1dkTc',
    appId: '1:301900713627:ios:e4783cd9ed38c0aa9bc03e',
    messagingSenderId: '301900713627',
    projectId: 'chatapplication-47e35',
    storageBucket: 'chatapplication-47e35.appspot.com',
    iosBundleId: 'com.example.groupChatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSqDB2rD0hgD-tPf10MzrGALNVBL1dkTc',
    appId: '1:301900713627:ios:e4783cd9ed38c0aa9bc03e',
    messagingSenderId: '301900713627',
    projectId: 'chatapplication-47e35',
    storageBucket: 'chatapplication-47e35.appspot.com',
    iosBundleId: 'com.example.groupChatApplication',
  );
}
